logging:
  syslog: $(False if devel.local else True)
  log_dir: /var/log/boss
  default:
    level: $("DEBUG" if devel.debug else "INFO")
    format_string: "[{record.time:%Y-%m-%d %H:%M:%S}][{record.extra[request_id]:>6}]{record.level_name:>7}: {record.message}"
    handler_list:
      - Null
      - ${"FailureFile" if logging.syslog else "FailureSyslog"}
      - Sentry
      - ApiFile
      - ${"AppFile" if logging.syslog else "AppSyslog"}

  handlers:
    stderr:
      type: StderrHandler
      level: "DEBUG"

    FailureFile:
      type: FileHandler
      filename: $(join(logging.log_dir, "failures.log"))
      delay: true
      level: "WARNING"
      encoding: utf-8

    FailureSyslog:
      type: SyslogHandler
      application_name: failures
      level: "WARNING"

    AppFile:
      type: FileHandler
      filename: $(join(logging.log_dir, "__APP__.log"))
      delay: true
      bubble: true
      finger_cross: false
      filter: without_api_filter
      encoding: utf-8

    ApiFile:
      type: FileHandler
      filename: $(join(logging.log_dir, "__APP__.log"))
      delay: true
      bubble: true
      finger_cross: false
      filter: only_api_filter
      format_string: "|{record.time:%Y-%m-%d %H:%M:%S}| {record.extra[request_id]}|{record.message}"
      level: NOTICE
      encoding: utf-8

    AppSyslog:
      type: SyslogHandler
      application_name: __APP__
      bubble: true
      finger_cross: false
      filter: without_api_filter


    Sentry:
      type: SentryHandler
      dsn: $(sentry.backend)
      level: ERROR
      bubble: true

      tags:
        region: $(region)
        az: $(availability_zone)
        host_ip: ${environ.get("DOCKER_IPADDR", "host_ip")}
        host_name: ${environ.get("DOCKER_FQDN", "docker_host_name")}

    Null:
      type: NullHandler

  finger_cross:
    buffer_size: 0
    reset: false
    action_level: WARNING
    bubble: true

  applications:
    stderr:
      handlers:
        - Null
        - stderr

    backend_admin:
    backend_cabinet:
    celery_worker:
    fitter:
    test:
      handlers:
        - Null
        - ${"FailureFile" if logging.syslog else "FailureSyslog"}
        - ApiFile
        - ${"AppFile" if logging.syslog else "AppSyslog"}
